# Copyright (c) 2026 Clove Twilight
# Licensed under the ESAL-2.0 Licence.
# See LICENCE.md in the project root for full licence information.
services:
  personal:
    build:
      context: ./personal
      dockerfile: Dockerfile
    container_name: personal
    ports:
      - "127.0.0.1:5002:5002"
    restart: unless-stopped

  dough-front:
    build:
      context: ./system
      dockerfile: Dockerfile
    container_name: system
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:5001:5001"

  inbox:
    build:
      context: ./mailbox
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4040:4040"
    volumes:
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
      - "./mail-data:/app/data"
    restart: unless-stopped

volumes:
  backend_data:
  backend_avatars:
  
