# compose.yml
# Copyright (c) 2026 Clove Twilight
# Licensed under the ESAL-2.0 Licence.
# See LICENCE.md in the project root for full licence information.
services:
  personal:
    image: doughmination/personal:latest
    container_name: personal
    ports:
      - "127.0.0.1:4050:4050"
    restart: unless-stopped

  blog:
    image: doughmination/blog:latest
    container_name: blog
    ports:
      - "127.0.0.1:4010:4010"
    restart: unless-stopped

  info:
    image: doughmination/info:latest
    container_name: info
    ports:
      - "127.0.0.1:4020:4020"
    restart: unless-stopped

  system:
    image: doughmination/system:latest
    container_name: system
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:4030:4030"

  inbox:
    image: doughmination/mailbox:latest
    container_name: inbox
    ports:
      - "127.0.0.1:4040:4040"
    networks:
      - infra
    volumes:
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
      - "./mail-data:/app/data"
    restart: unless-stopped

networks:
  infra:
    external: true

volumes:
  backend_data:
  backend_avatars: