# .github/workflows/personal.yml
# Copyright (c) 2026 Clove Twilight
# Licensed under the ESAL-2.0 Licence.
# See LICENCE.md in the project root for full licence information.

name: personal

on:
  push:
    branches:
      - main
    paths:
      - "personal/**"
      - ".github/workflows/personal.yml"
      - ".github/workflows/docker-build.yml"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      service: personal
    secrets: inherit
